version: '3'

services:
  # Twój Backend (odpowiednik 'mysql-db' u nauczyciela )
  pogoda-api:
    build: ./backend
    container_name: website_backend
    ports:
      - "8081:5000"
    networks:
      - my-network

  # Twój Frontend (odpowiednik 'spring-boot-app'a)
  moj-nginx:
    build: ./frontend
    container_name: website_frontend
    ports:
      - "8080:80"
    depends_on:
      - pogoda-api  # Frontend uruchomi się po Backendzie
    networks:
      - my-network

# Definicja sieci 
networks:
  my-network:
