apiVersion: v1
kind: Service
metadata:
  name: pogoda-api  # <-- TO MUSI PASOWAÄ† DO NGINX.CONF
spec:
  selector:
    app: pogoda-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
