apiVersion: apps/v1
kind: Deployment
metadata:
  name: pogoda-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pogoda-frontend
  template:
    metadata:
      labels:
        app: pogoda-frontend
    spec:
      containers:
      - name: frontend
        image: moj-frontend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
